/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExerciseDto } from '../../models/exercise-dto';
import { ExerciseForm } from '../../models/exercise-form';

export interface Create1$Params {
      body?: {
'form': ExerciseForm;
'media'?: Blob;
}
}

export function create1(http: HttpClient, rootUrl: string, params?: Create1$Params, context?: HttpContext): Observable<StrictHttpResponse<ExerciseDto>> {
  const rb = new RequestBuilder(rootUrl, create1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExerciseDto>;
    })
  );
}

create1.PATH = '/exercise';
