/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExerciseDto } from '../../models/exercise-dto';

export interface Detail1$Params {
  id: number;
}

export function detail1(http: HttpClient, rootUrl: string, params: Detail1$Params, context?: HttpContext): Observable<StrictHttpResponse<ExerciseDto>> {
  const rb = new RequestBuilder(rootUrl, detail1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExerciseDto>;
    })
  );
}

detail1.PATH = '/exercise/{id}';
