/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExerciseDto } from '../../models/exercise-dto';

export interface Export1$Params {
  query?: string;
}

export function export1(http: HttpClient, rootUrl: string, params?: Export1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExerciseDto>>> {
  const rb = new RequestBuilder(rootUrl, export1.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExerciseDto>>;
    })
  );
}

export1.PATH = '/exercise';
