/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PresetDto } from '../../models/preset-dto';

export interface DetailUnlockable$Params {
  id: number;
}

export function detailUnlockable(http: HttpClient, rootUrl: string, params: DetailUnlockable$Params, context?: HttpContext): Observable<StrictHttpResponse<PresetDto>> {
  const rb = new RequestBuilder(rootUrl, detailUnlockable.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PresetDto>;
    })
  );
}

detailUnlockable.PATH = '/preset/unlockable/{id}';
