/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnlockablePresetDto } from '../../models/unlockable-preset-dto';

export interface ExportUnlockable$Params {
}

export function exportUnlockable(http: HttpClient, rootUrl: string, params?: ExportUnlockable$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UnlockablePresetDto>>> {
  const rb = new RequestBuilder(rootUrl, exportUnlockable.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UnlockablePresetDto>>;
    })
  );
}

exportUnlockable.PATH = '/preset/unlockable';
