/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthSessionDto {
  id?: number;
  memberRole?: 'ADMIN' | 'MEMBER';
  pseudo?: string;
}
