/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthSessionDto } from '../models/auth-session-dto';
export interface AuthTokenDto {
  member?: AuthSessionDto;
  token?: string;
}
