/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExerciseForm {
  description?: string;
  exerciseTargets?: Array<'ABS' | 'BICEPS' | 'CALVES' | 'CHEST' | 'FOREARMS' | 'GLUTES' | 'HAMSTRINGS' | 'LATS' | 'LOWERBACK' | 'OBLIQUES' | 'QUADS' | 'SHOULDERS' | 'SPECIALS' | 'TRAPS' | 'TRICEPS'>;
  name?: string;
}
