/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PresetExerciseForm } from '../models/preset-exercise-form';
export interface PresetForm {
  name?: string;
  presetExercises?: Array<PresetExerciseForm>;
  presetType: 'AD' | 'FREE' | 'PAID';
}
