/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExerciseDto } from '../models/exercise-dto';
export interface PresetExerciseDto {
  exercise?: ExerciseDto;
  position?: number;
}
