/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PresetDto } from '../models/preset-dto';
export interface UnlockablePresetDto {
  preset?: PresetDto;
  unlocked?: boolean;
}
